site_name: S AI vault
theme:
  name: material
  logo: icons/vault.png
  favicon: icons/valut.png
  features:
    - navigation.tabs
    - navigation.sections
    # - toc.integrate
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gpurnasai
    - icon: fontawesome/brands/github
      link: https://github.com/purnasai
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/purnasai-gudikandula/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@purnasaigudikandula

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


nav:
  - 'Home': 
      - 'Profile': 'index.md'

  - "Python":
    - "Python": "python/index.md"
    - "Bytes": "python/Bytes.md"
    - "Better programming":
      - "Tmux": "python/terminal_multiplexer.md"
      - "property method": "python/property.md"
      - "getter setter in class": "python/property.md"
      - "private variable": "python/property.md"
      - "static method": "python/static_method.md"
      - "Decorators": "python/Decorators.md"
      - "Generators": "python/generators.md"
      - "Pydantic": "python/pydantic.md"
    - "DSA":
      - "Data structures": "python/Datastructures.md"
      - "Advanced": "python/advanced_python.md"
      - "Algorithms": "python/algorithms.md"
    - "Object Oriented":      
      - "OOPS": "python/OOPS.md"
    - "Efficient python":
      - "speed and memory": "python/efficient_python.md"
      - "Multithread and processing": "python/multithread_multiprocess.md"

  - 'Math':
      - "Math": 'Math/index.md'
  
  - "Machine Learning":
      - "ML": "ML/index.md"
      - "Pipeline": "ML/lifecycle.md"
      - "Algorithms": "ML/algorithms.md"
      - "Feature selection": "ML/feature_selection.md"
      - "Hyperparameter tune": "ML/hyperparameter_tune.md"
      - "Explainability": "ML/Explainability.md"

  
  - "Deep Learning":
      - "DL": "DL/index.md"
      - "Activations": "DL/activations.md"
      - "Normalization": "DL/normalization.md"
      - "Trackers": "DL/trackers.md"

  - "Computer Vision":
    - "Old CV":
        - "Old CV": "Old_CV/index.md"
        - "Gradcam": "Old_CV/grad_cam.md"
    
    - "New CV":
        - "New CV": "New_CV/index.md"
        # - "Multimodels": "New_CV/MultiModels.md"

  - "Natural Language Processing":
    - "Old NLP":
        - "Old NLP": "Old_NLP/index.md"
        - "Pre-processing": "Old_NLP/preprocessing.md"
        - "Encodings": "Old_NLP/encodings.md"
        - "Tokenizers": "Old_NLP/tokenizers.md"
        - "One-gram/Bi-gram/N-gram": "Old_NLP/ngrams.md"
        - "Word2vec/Tf-idf": "Old_NLP/word2vec.md"
        - "Embeddings": "Old_NLP/embeddings.md"


    - "New NLP":
        - "New NLP": "New_NLP/index.md"
        - "QLora": "New_NLP/QLora.md"

  - "MLOPS":
      - "MLOPs": "MLOPS/index.md"
      - "Docker": "MLOPS/Docker.md"
      - "Git": "MLOPS/Git.md"
      
  - "Notes":
      - "Talks":
        - "Sample Talk": "Notes/talks.md"
      - "YT Videos":
        - "know train depoly of LLMs": "Notes/know_train_deploy_LLMs.md"
      - "Blogs":
        - "Finetuning LLM": "Notes/finetuning_LLMs.md"

  - "Others":
      - "Terminologies": "Others/terminologies.md"
      - "API Implementation": "Others/Api_Implementation.md"
      - "Frameworks": "Others/frameworks.md"
      - "Annotation tool": "Others/annotation_tools.md"
      - "Free GPUs" : "Others/free_gpus.md"
      - "Notes Taking": Others/notes_taking.md
      - "Observations": Others/observations.md
      - "People": Others/people_to_follow.md
      - "Quick Demo libs": Others/quick_apps.md
      - "Tesseract": Others/tesseract_in_colab.md
      - "Tutorials": Others/tutorails.md
      - "Gpu understanding": Others/understanding_gpu.md

  - "Project Maintainence":
      - "Project Maintainence": "project_maintainence/index.md"
      - "PMP course": "project_maintainence/PMP course.md"
      - "Project structure": "project_maintainence/project_structure.md"
      - "Source title": "project_maintainence/source_title.md"
      - "Reproducibility": "project_maintainence/reproducibility.md"
      - "Memory release": "project_maintainence/memory_release.md"

copyright: |
  &copy; 2024 <a href="https://github.com/purnasai"  target="_blank" rel="noopener">Purnasai G</a>